[workspace]
members = [
    "spwn",
    "parser",
    "shared",
    "errors",
    "levelstring",
    "editorlive",
    "compiler",
    "optimizer",
    "docgen",
    "spwn-web",
]

[profile.release]
debug = true
